// Code generated by "stringer -type=StatusFlag"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SERVER_STATUS_IN_TRANS-1]
	_ = x[SERVER_STATUS_AUTOCOMMIT-2]
	_ = x[SERVER_MORE_RESULTS_EXISTS-4]
	_ = x[SERVER_STATUS_NO_GOOD_INDEX_USED-8]
	_ = x[SERVER_STATUS_NO_INDEX_USED-16]
	_ = x[SERVER_STATUS_CURSOR_EXISTS-32]
	_ = x[SERVER_STATUS_LAST_ROW_SENT-64]
	_ = x[SERVER_STATUS_DB_DROPPED-128]
	_ = x[SERVER_STATUS_NO_BACKSLASH_ESCAPES-256]
	_ = x[SERVER_STATUS_METADATA_CHANGED-512]
	_ = x[SERVER_QUERY_WAS_SLOW-1024]
	_ = x[SERVER_PS_OUT_PARAMS-2048]
	_ = x[SERVER_STATUS_IN_TRANS_READONLY-4096]
	_ = x[SERVER_SESSION_STATE_CHANGED-8192]
}

const _StatusFlag_name = "SERVER_STATUS_IN_TRANSSERVER_STATUS_AUTOCOMMITSERVER_MORE_RESULTS_EXISTSSERVER_STATUS_NO_GOOD_INDEX_USEDSERVER_STATUS_NO_INDEX_USEDSERVER_STATUS_CURSOR_EXISTSSERVER_STATUS_LAST_ROW_SENTSERVER_STATUS_DB_DROPPEDSERVER_STATUS_NO_BACKSLASH_ESCAPESSERVER_STATUS_METADATA_CHANGEDSERVER_QUERY_WAS_SLOWSERVER_PS_OUT_PARAMSSERVER_STATUS_IN_TRANS_READONLYSERVER_SESSION_STATE_CHANGED"

var _StatusFlag_map = map[StatusFlag]string{
	1:    _StatusFlag_name[0:22],
	2:    _StatusFlag_name[22:46],
	4:    _StatusFlag_name[46:72],
	8:    _StatusFlag_name[72:104],
	16:   _StatusFlag_name[104:131],
	32:   _StatusFlag_name[131:158],
	64:   _StatusFlag_name[158:185],
	128:  _StatusFlag_name[185:209],
	256:  _StatusFlag_name[209:243],
	512:  _StatusFlag_name[243:273],
	1024: _StatusFlag_name[273:294],
	2048: _StatusFlag_name[294:314],
	4096: _StatusFlag_name[314:345],
	8192: _StatusFlag_name[345:373],
}

func (i StatusFlag) String() string {
	if str, ok := _StatusFlag_map[i]; ok {
		return str
	}
	return "StatusFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
